name: Release

on:
  push:
    tags: [ "v*.*.*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: |
          ./gradlew packageDeb
          ./gradlew packageRpm
          ./gradlew packageAppImage

      - name: Save built files
        uses: actions/upload-artifact@v6
        with:
          name: linux
          path: |
            build/compose/binaries/main-release/**/*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: |
          ./gradlew packageMsi
          ./gradlew packageExe

      - name: Save built files
        uses: actions/upload-artifact@v6
        with:
          name: windows
          path: |
            build/compose/binaries/main-release/**/*

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: |
          ./gradlew packageDmg

      - name: Save built files
        uses: actions/upload-artifact@v6
        with:
          name: macos
          path: |
            build/compose/binaries/main-release/**/*

  release:
    runs-on: ubuntu-latest
    needs: [ build-windows, build-linux, build-macos ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get all build outputs
        uses: actions/download-artifact@v7
        with:
          path: exec/

      - name: Display structure of downloaded files
        run: tree exec/

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Altivion
          prerelease: true
          generate_release_notes: true
          files: |
            exec/*
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: dhzdhd/altivion
